import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {neobrutalism,shadesOfPurple} from '@clerk/themes';
import { ClerkProvider } from '@clerk/nextjs'
import {ToastProvider} from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LMS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: shadesOfPurple,
      variables: { colorPrimary: 'yellow' },
      signIn: { 
        baseTheme: shadesOfPurple, 
        variables: { colorPrimary: 'yellow' }
      }
    }}
    >
      
      <html lang="en">
        <body className={inter.className } >
          <ConfettiProvider />
          <ToastProvider />
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
